### ISSUE TITLE
not able to connect to aws db using RPostgreSQL

### ISSUE THREAD

**Issue by merlinoa** [databrew/benchmark#6]
I am not able to connect to the database using the RPostgreSQL driver.  When I try to make the connection using this code:

```
con_test <- DBI::dbConnect(
  RPostgreSQL::PostgreSQL(),
  host = "<name>.cosjv4zx2mww.us-east-1.rds.amazonaws.com",
  port = 5432,
  dbname = "ARL",
  user = "postgres",
  password = "<password>"
)
```

I get the following error

```
Error in postgresqlNewConnection(drv, ...) : 
  RS-DBI driver: (could not connect postgres@<name>.cosjv4zx2mww.us-east-1.rds.amazonaws.com:5432 on dbname "ARL": FATAL:  no pg_hba.conf entry for host "172.56.2.94", user "postgres", database "ARL", SSL off
)
```

I can connect to the database without issue using the `RPostgres` driver rather than the `RPostgreSQL` driver using the following identical code except the driver is switched:

```
con_test <- DBI::dbConnect(
  RPostgres::Postgres(),
  host = "<name>.cosjv4zx2mww.us-east-1.rds.amazonaws.com",
  port = 5432,
  dbname = "ARL",
  user = "postgres",
  password = "<password>"
)
```

I can also connect without issue using pgAdmin and Navicat.

I do not want to have to use the switch to `RPostgres` because `RPostgres` and `RPostgreSQL` have different methods for converting R variable types to Postgres types which cause the Postgres statements and functions to fail with errors.  

This SO answer suggests we may be able to edit some files on the server to get it working https://dba.stackexchange.com/questions/83984/connect-to-postgresql-server-fatal-no-pg-hba-conf-entry-for-host

Other SO answers say they just switched to `RPostgres`.  I don't think switching is an option for us.  Please let me know if you have any thoughts on this matter.  Any help is very very appreciated.

**Comment by merlinoa** [comment]
closed for MAC by reinstalling `RPostgreSQL` per these instructions.

http://www.developersite.org/1000-29636-How-can-I-compile-RpostgreSQL-with-libssl-and-libpg-and-SSL-activation

**Comment by njlyon0** [comment]
Hi! The instructions link above doesn't work any more, would it be possible to get those instructions written out for myself and future Mac users who experience this issue?
